export type Institutions = {
  id: number;
  institution_id: string;
  institution: string;
  active: boolean;
  uploaded_time: string;
  logo_url: string;
  region: string;
  investor_type: string;
  contact: string | null;
  email: string | null;
  date_created: string;
  date_updated: string;
  uploaded_time_caspio: string;
  whale_wisdom_filer_id: string | number;
  proxy_advisor_influence?: string;
  unpri_signatory?: boolean;
  documents?: InstitutionDocument[];
  investor_profile_id?: number;
};

export type InstitutionDocument = {
  month: string;
  id: number;
  name: string;
  document_name?: string;
  year: number;
  link: string;
  document_type: string;
  tags: string;
  priority: string;
  active: boolean;
  linked_to_summary: boolean;
  linked_to_engagement_priorities: boolean;
  linked_to_reporting_expectation: boolean;
  linked_to_esg_integration: boolean;
  linked_to_voting_guidelines: boolean;
  created_by_name?: string;
  date_created?: string;
  is_deleted?: boolean;
};
